name: Run main.py Once

on:
  workflow_dispatch: # Use workflow dispatch instead of schedule

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Logs Directory (optional)
        # This step creates the logs directory if it doesn't exist.
        # Comment it out if you don't need to create the directory beforehand.
        run: |
          mkdir -p logs

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute py script
        env:
          uri: ${{ secrets.DB_ACCESS_URI }}  # Assuming DB_ACCESS_URI is set as a secret
          base_url: ${{ secrets.BASE_URL }}  # Assuming BASE_URL is set as a secret
          headers: ${{ secrets.GITHUB_HEADERS }}    # Assuming HEADERS is set as a secret

      - name: Commit files (optional)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: Push changes (optional)
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Only push if needed